spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: reserve-product-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    properties:
      spring:
        json:
          trusted:
            packages: "neoflex.prod.practice.dto"

kafka:
  topics:
    reserve:
      product: reserve-product

server:
  port: 8082
  url: "http://localhost:${server.port}"