spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${PG_USER}
    password: ${PG_PASSWORD}
    url: jdbc:postgresql://${PRODUCTS_SERVICE:localhost}:5432/${PRODUCTS_DB}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: reserve-product-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
    properties:
      schema.registry.url: ${SCHEMA_REGISTRY_SERVICE:localhost}:8081
      specific.avro.reader: true

kafka:
  topics:
    reserve:
      product: reserve-product

management:
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://${JAEGER_SERVICE:localhost}:4317

otel:
  resource:
    attributes:
      service.name: ProductService
  traces:
    exporter: otlp
  metrics:
    exporter: otlp
  logs:
    exporter: none
  exporter:
    otlp:
      endpoint: http://${JAEGER_SERVICE:jaeger}:4318

server:
  port: 8083
  url: "http://localhost:${server.port}"