management:
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://${JAEGER_SERVICE:localhost}:4317

otel:
  resource:
    attributes:
      service:
        name: ${spring.application.name}