spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${PG_USER}
    password: ${PG_PASSWORD}
    url: jdbc:postgresql://${ORDERS_SERVICE:localhost}:5432/${ORDERS_DB}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema.registry.url: http://${SCHEMA_REGISTRY_SERVICE:localhost}:8081

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml

kafka:
  topics:
    reserve:
      product: reserve-product

server:
  port: 8082
  url: "http://localhost:${server.port}"

management:
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://${JAEGER_SERVICE:localhost}:4317

otel:
  resource:
    attributes:
      service.name: OrdersService
  traces:
    exporter: otlp
  metrics:
    exporter: none
  logs:
    exporter: none
  exporter:
    otlp:
      endpoint: http://${JAEGER_SERVICE:jaeger}:4318
